<?php

namespace backend\models;

use Yii;
use yii\base\Model;
use yii\helpers\Url;

/**
 * Signup form
 */
class SignupForm extends Model
{
    public $username;
    public $email;
    public $password;
    public $rePassword;
    public $verificationCode;


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['username', 'filter', 'filter' => 'trim'],
            [['username'], 'required'],
            ['username', 'unique', 'targetClass' => '\common\models\User', 'message' => 'This username has already been taken.'],
            ['username', 'string', 'min' => 6, 'max' => 12],
            ['email', 'filter', 'filter' => 'trim'],
            ['email', 'required'],
            ['email', 'email'],
            ['email', 'string', 'max' => 255],
            ['email', 'unique', 'targetClass' => '\common\models\User', 'message' => 'This email address has already been taken.'],

            [['password', 'rePassword'], 'required'],
            [['password', 'rePassword'], 'string', 'min' => 6, 'max' => 12],
            ['password', 'compare', 'compareAttribute' => 'rePassword', 'operator' => '===', 'message' => '两次输入的密码必须一致'],
            ['verificationCode', 'captcha'],
        ];
    }

    public function attributeLabels()
    {
        $parent = parent::attributeLabels(); // TODO: Change the autogenerated stub
        $parent['verificationCode'] = Yii::t('app', '验证码');
        return $parent;
    }

    /**
     * @return bool
     */
    public function signup()
    {
        if (!$this->validate()) {
            return false;
        }
        $admin = new Admin();
        $admin->username = $this->username;
        $admin->email = $this->email;
        $admin->setPassword($this->password);
        $admin->generateAuthKey();
        if (!$admin->save()) {
            //var_dump($admin->errors);die;
            return false;
        }
        return true;
    }
}
